# Generated by Django 2.2 on 2019-12-19 19:32

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('student_class', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=2)),
                ('class_type', models.CharField(choices=[('1-1', 'One-to-One Class'), ('1-n', 'One-to-Many Class')], max_length=5)),
                ('hourly_rate', models.IntegerField()),
                ('methodology', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Class Listings',
            },
        ),
        migrations.CreateModel(
            name='notisfications_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notisfications_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('sub_detail', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('skype_id', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=1)),
                ('identity_document', models.FileField(upload_to='')),
                ('curriculum_vitae', models.TextField()),
                ('about', models.TextField()),
                ('languages_spoken', models.ManyToManyField(to='core.languages')),
            ],
            options={
                'verbose_name_plural': 'Tutors',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('skype_id', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=1)),
                ('student_class', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('notisfications', models.ManyToManyField(to='core.notisfications_type')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('payment_id', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listings')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.StudentProfile')),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='class_slot',
            field=models.ManyToManyField(to='core.TimeSlots'),
        ),
        migrations.AddField(
            model_name='listings',
            name='subject',
            field=models.ManyToManyField(to='core.subjects'),
        ),
        migrations.AddField(
            model_name='listings',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TutorProfile'),
        ),
        migrations.CreateModel(
            name='class_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listings')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StudentProfile')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TimeSlots')),
            ],
        ),
    ]
