# Generated by Django 2.2 on 2019-12-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_request',
            options={'verbose_name_plural': 'Class Requests'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'Languages Spoken'},
        ),
        migrations.AlterModelOptions(
            name='notisfications_type',
            options={'verbose_name_plural': 'Notisfication Types'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='timeslots',
            options={'verbose_name_plural': 'Time Slots'},
        ),
    ]
