# Generated by Django 2.2 on 2019-12-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191221_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_request',
            name='accepted_status',
            field=models.BooleanField(default=0),
        ),
    ]
